In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data.csv')

In [3]:
data

id    name  salary address
0    1   name1    1234     ad1
1    2   name2    4567     ad2
2    3   name3    8910     ad1
3    4   name4    1235     ad2
4    5   name5    4568     ad3
5    6   name6    8911     ad2
6    7   name7    1236     ad3
7    8   name8    4569     ad4
8    9   name9    8912     ad3
9   10  name10    1237     ad4
10  11  name11    4570     ad5
11  12  name12    8913     ad4
12  13  name13    1238     ad5
13  14  name14    4571     ad6
14  15  name15    8914     ad5
15  16  name16    1239     ad6
16  17  name17    4572     ad7
17  18  name18    8915     ad6
18  19  name19    1240     ad7
19  20  name20    4573     ad8
20  21  name21    8916     ad7
21  22  name22    1241     ad8
22  23  name23    4574     ad9
23  24  name24    8917     ad8
24  25  name25    1242     ad9
25  26  name26    4575    ad10
26  27  name27    8918     ad9
27  28  name28    1243    ad10

In [4]:
data['salary'].mean()

4776.785714285715

In [5]:
data[data['salary']<data['salary'].mean()]

id    name  salary address
0    1   name1    1234     ad1
1    2   name2    4567     ad2
3    4   name4    1235     ad2
4    5   name5    4568     ad3
6    7   name7    1236     ad3
7    8   name8    4569     ad4
9   10  name10    1237     ad4
10  11  name11    4570     ad5
12  13  name13    1238     ad5
13  14  name14    4571     ad6
15  16  name16    1239     ad6
16  17  name17    4572     ad7
18  19  name19    1240     ad7
19  20  name20    4573     ad8
21  22  name22    1241     ad8
22  23  name23    4574     ad9
24  25  name25    1242     ad9
25  26  name26    4575    ad10
27  28  name28    1243    ad10

In [6]:
data[data['address']=="ad1"]

id   name  salary address
0   1  name1    1234     ad1
2   3  name3    8910     ad1

In [7]:
data[data['address']=="ad1"].sum()

id                  4
name       name1name3
salary          10144
address        ad1ad1
dtype: object

In [10]:
data[data['address']=="ad1"].sum()['salary']

10144

In [11]:
data.groupby('address')

In [12]:
data.groupby('address').mean()

id       salary
address                   
ad1       2.0  5072.000000
ad10     27.0  2909.000000
ad2       4.0  4904.333333
ad3       7.0  4905.333333
ad4      10.0  4906.333333
ad5      13.0  4907.333333
ad6      16.0  4908.333333
ad7      19.0  4909.333333
ad8      22.0  4910.333333
ad9      25.0  4911.333333

In [13]:
data.groupby('address').sum()

id  salary
address            
ad1       4   10144
ad10     54    5818
ad2      12   14713
ad3      21   14716
ad4      30   14719
ad5      39   14722
ad6      48   14725
ad7      57   14728
ad8      66   14731
ad9      75   14734

In [14]:
data.groupby('address').max()

id    name  salary
address                    
ad1       3   name3    8910
ad10     28  name28    4575
ad2       6   name6    8911
ad3       9   name9    8912
ad4      12   name8    8913
ad5      15  name15    8914
ad6      18  name18    8915
ad7      21  name21    8916
ad8      24  name24    8917
ad9      27  name27    8918

In [15]:
#http://pandas.pydata.org/pandas-docs/stable/10min.html
#http://pandas.pydata.org/pandas-docs/version/0.18.1/visualization.html
#https://drive.google.com/drive/folders/0B1-Mq72jCFFbSTZWY3VwVU5kV0U

In [16]:
l=[1,20.3,"pytho",[1,2,3,4]]

In [18]:
import numpy as np

In [20]:
ar1=np.array([10,20,30,40])
l1=[10,20,30,40]

In [21]:
ar1

array([10, 20, 30, 40])

In [22]:
ar2=np.array([10,10.2,"python"])

In [23]:
ar2

array(['10', '10.2', 'python'], 
      dtype='|S32')

In [24]:
l.pop

<function pop>

In [25]:
ar1=np.arange(10,30,2)

In [26]:
ar1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [28]:
range(0,1,0.1)

TypeError: range() integer step argument expected, got float.

In [30]:
np.arange(0,1,0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [31]:
l1=[[10,20,30,40],[1,2,3,4],[5,6,7,8]]

In [32]:
len(l)

4

In [34]:
l1[0:2]

[[10, 20, 30, 40], [1, 2, 3, 4]]

In [35]:
ar1=np.arange(20)

In [36]:
ar1 = ar1.reshape(5,4)

In [37]:
ar1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [38]:
ar1.max()

19

In [39]:
ar1.min()

0

In [40]:
ar1.sum()

190

In [41]:
ar1.sum(axis=0)

array([40, 45, 50, 55])

In [42]:
ar1.sum(axis=1)

array([ 6, 22, 38, 54, 70])

In [43]:
ar1.min(axis=0)

array([0, 1, 2, 3])

In [44]:
ar1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [45]:
ar1.size

20

In [47]:
ar1.shape

(5, 4)

# 

In [48]:
ar1.ndim

2

In [50]:
ar1.dtype

dtype('int64')

In [59]:
l2=[10,20,30,1,-2]
import matplotlib.pyplot as plt
plt.plot(l2,'r+')
plt.show()

In [58]:
plt.plot?

In [60]:
l2=[10,20,30,1,-2]
import matplotlib.pyplot as plt
plt.plot(l2)
plt.show()

In [62]:
l1=range(10)
l2=[x**2 for x in l1]

In [63]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [64]:
l2

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [67]:
plt.plot(l1,l2)
plt.show()

In [68]:
plt.plot?